export const roles = ['admin', 'requester', 'screener', 'packer', 'shipper'] as const;

export type RoleType = (typeof roles)[number];

export const TOKEN_COOKIE_NAME = 'vka_token__new';

export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Congo-Brazzaville)',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Holy See',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine State',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const requestUrgencies = ['Urgent (<1 week)', 'Short-term (1–2 months)', 'Medium-term (3–6 months)', 'Long-term (>6 months)'] as const;

export const applicationTypes = ['Food', 'Health', 'Non-Food'] as const;

export const foodMatrix: Record<string, string[]> = {
  Beverage: ['Carbonated', 'Juice', 'Alcoholic', 'RTD coffee & tea', 'Energy', 'Flavoured water'],
  'Bakery & Cereals': ['Bread', 'Cakes', 'Biscuits', 'Cereals', 'Snack bars'],
  'Dairy & Alternatives': ['Milk', 'Yogurt', 'Cheese', 'Plant-based', 'Ice cream'],
  Confectionery: ['Sugar', 'Chocolate', 'Chewing gum', 'Lozenges'],
  'Savoury & Culinary': ['Soups', 'Sauces', 'Ready meals', 'Snacks', 'Instant noodles'],
  'Meat & Plant-Based Proteins': ['Processed meat', 'Seafood', 'Analogues'],
  Snacks: ['Extruded', 'Nuts', 'Coated snacks'],
};

export const healthApplications = ['Nutraceuticals', 'Infant nutrition', 'Medical nutrition'] as const;

export const nonFoodApplications = ['Pharma', 'Oral Care', 'Personal Care', 'Cosmetics'] as const;

export const processingConditionsList = ['Heat', 'UHT', 'Baking', 'Extrusion', 'Acidic pH', 'Neutral pH', 'Fermentation', 'Freezing'] as const;

export const shelfLifeExpectations = ['<6 months', '6–12 months', '>12 months'] as const;

export const formatRequiredOptions = ['Liquid', 'Powder', 'Encapsulated', 'No preference'] as const;

export const legalStatusOptions = ['Natural', 'Nature-Identical', 'Synthetic'] as const;

export const certificationsRequiredOptions = ['Halal', 'Kosher', 'Both', 'None'] as const;

export const sampleVolumeOptions = ['30g', '50g', '100g', 'other'] as const;

export const documentsNeededOptions = ['TDS', 'SDS', 'Halal', 'Kosher', 'Other'] as const;

export const accountTypeOptions = ['Strategic', 'Growth', 'New', 'Transactional'] as const;

export const commercialPotentialOptions = ['Trial', 'Pilot <1MT', 'Commercial >10MT'] as const;

export const internalPriorityLevels = ['High', 'Medium', 'Low'] as const;
